sudo: required
services:
  - docker

before_install:
  - docker build -t mihaelagog/multi-docker -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true mihaelagog/multi-docker npm test -- --coverage

after_success:
 - docker build -t mihaelagog/multi-client ./client
 - docker build -t mihaelagog/multi-nginx ./nginx
 - docker build -t mihaelagog/multi-server ./server
 - docker build -t mihaelagog/multi-worker ./worker
#Log to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take images and push to docker hub
 - docker push mihaelagog/multi-client
 - docker push mihaelagog/multi-nginx
 - docker push mihaelagog/multi-server
 - docker push mihaelagog/multi-worker